#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
# we read a json stdin {"vars1":true, "var2":"foo", "vars3": 3} and we writ it to .config/state/environment
# Upper case to set environment variable and minor case to read from stdin
# - DATABASE_NAME=data.db
# - INIT_GROUP=zusam
# - INIT_PASSWORD=zusam
# - INIT_USER=zusam
INIT_GROUP = data.get('init_group', 'zusam')
INIT_PASSWORD = data.get('init_password', 'zusam')
INIT_USER = data.get('init_user', 'zusam')
DATABASE_NAME = data.get('database_name', 'data.db')

# Write the environment variables to the agent
app_config = {
    'DATABASE_NAME': DATABASE_NAME,
    'INIT_GROUP': INIT_GROUP,
    'INIT_PASSWORD': INIT_PASSWORD,
    'INIT_USER': INIT_USER
}
agent.write_envfile("app.env", app_config)

#agent.dump_env()
